### ISSUE TITLE
Multiple `uuids`: `'NoneType' object has no attribute 'modality_name'`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#19]
```
>>> from hubmap_api_py_client import Client
>>> uuids = ['14946a8eb12f2d787302f818b72fdc4e', '1ca63edfa35971f475c91d92f4a70cb0']
>>> gene_name = 'VIM'
>>> min_gene_expression = 1
>>> client = Client('https://cells.api.hubmapconsortium.org/api/')
>>> dataset_set = client.select_datasets(where='dataset', has=[uuids])
>>> results = list(dataset_set.get_list(values_included=[f'{gene_name} > {min_gene_expression}']))
Traceback (most recent call last):
...
hubmap_api_py_client.errors.ClientError: 'NoneType' object has no attribute 'modality_name'
```
Try it with just one uuid:
```
>>> uuids = ['14946a8eb12f2d787302f818b72fdc4e']
>>> results = list(dataset_set.get_list(values_included=[f'{gene_name} > {min_gene_expression}']))
>>> results
[{'uuid': '14946a8eb12f2d787302f818b72fdc4e', 'values': 30.224828934506355}]
```

**Comment by SFD5311** [comment]
Appears to me to be fixed with commit:
https://github.com/hubmapconsortium/cross_modality_query/commit/652041f7072d960bc9b53853954a6e7cf58aca1b
`>>> uuids = ['14946a8eb12f2d787302f818b72fdc4e', '1ca63edfa35971f475c91d92f4a70cb0']
>>> gene_name = 'VIM'
>>> min_gene_expression = 1
>>> client = Client('https://cells.api.hubmapconsortium.org/api/')
>>> dataset_set = client.select_datasets(where='dataset', has=[uuids])

>>> results = list(dataset_set.get_list(values_included=[f'{gene_name} > {min_gene_expression}']))
>>> print(results)`

`[{'uuid': '14946a8eb12f2d787302f818b72fdc4e', 'values': 30.224828934506355}, {'uuid': '1ca63edfa35971f475c91d92f4a70cb0', 'values': 21.16647973081237}]
`
