### ISSUE TITLE
Revert cell expression back to numbers instead of dict

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/cross_modality_query#20]
Just saw that we're now getting responses that looks like:
```
{"VIM > 1": 30.224828934506355}
```
We strongly prefer the original structure where only numbers are returned.
- Higher level issue: We're now using the API, so we need the responses to be stable. How to manage change is a separate discussion.
- If a dict is returned, the keys should be values that we passed in, rather than strings that will need to be constructed identically in two separate locations. To imagine an example that would cause problems... If we submit a number with a large number of decimal digits, your code may truncate it in a slightly different way than ours.
- Finally, if a dict is being returned, it should be in the JSON, rather than encoded within a string.

**Comment by SFD5311** [comment]
@mccalluc Just to be clear, this is specifically in the case where we're evaluating datasets to see what percentage of the cells within a dataset meet a certain condition, correct?

As in the result of client code that looks like this?:

datasets = client.select_datasets(where="gene", has=["VIM > 1"])
datasets.get_list(values_included=["VIM > 1"])

I will say, it was my initial intention for the responses to have the structure as above, as I felt it had better symmetry with the responses of other objects evaluations, and the fact that we were initially not getting that was a bug that escaped my attention early on.  That said, since you strongly prefer the original structure, I will revert it back to that.

**Comment by mccalluc** [comment]
@SFD5311 -- Just confirmed that the responses are back the way they were. Thanks!

At a higher level: We know you are going to expand the functionality, but going forward we really are going to need stability in response structures. API changes can't break client code. I think this is the time for you to also clarify the deployment process... You're probably going to want to move to a model where discrete features are separate PRs, CI passes before merging, and new features are deployed to the test instance for a bit of manual QA before being deployed to production.

The Cells API is going to be a really central part of the functionality of HuBMAP, and the processes need to be in place to make sure it's stable and reliable.

Regarding this particular feature -- Getting more symmetry between responses is not a bad thing! There are different ways that new features can be introduced in an existing API:
- Add a new endpoint
- Add new props in an existing response
- Make backward incompatible changes, but have both versions of the API available to clients during a migration window.

If we had atomic deployments of front-end and back-end code, it would be possible to release a new version of the client and a new version of the API at the same time, and not worry about backward compatibility, but we just don't have the dev-ops support to make it atomic like that.
